version: '3'

services:
  app:
    image: siddareddy/test:v1
    ports:
    - 8000:8000
  redis:
    image: 'redis:latest'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    volumes:
      - redis_data:/data
volumes:  
  redis_data:
  
